-- 코드를 입력하세요
-- 1. 시간대 테이블 0~23을 만들고
WITH hours AS (
  SELECT 0 AS hour
  UNION ALL SELECT 1
  UNION ALL SELECT 2
  UNION ALL SELECT 3
  UNION ALL SELECT 4
  UNION ALL SELECT 5
  UNION ALL SELECT 6
  UNION ALL SELECT 7
  UNION ALL SELECT 8
  UNION ALL SELECT 9
  UNION ALL SELECT 10
  UNION ALL SELECT 11
  UNION ALL SELECT 12
  UNION ALL SELECT 13
  UNION ALL SELECT 14
  UNION ALL SELECT 15
  UNION ALL SELECT 16
  UNION ALL SELECT 17
  UNION ALL SELECT 18
  UNION ALL SELECT 19
  UNION ALL SELECT 20
  UNION ALL SELECT 21
  UNION ALL SELECT 22
  UNION ALL SELECT 23
)

-- 2. 실제 데이터와 LEFT JOIN
SELECT 
  h.hour,
  COUNT(a.datetime) AS count
FROM hours AS h
LEFT JOIN ANIMAL_OUTS AS a
  ON HOUR(a.datetime) = h.hour
GROUP BY h.hour
ORDER BY h.hour;
