-- 코드를 작성해주세요

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_TREE AS T, ITEM_INFO AS I
    WHERE T.ITEM_ID = I.ITEM_ID 
        AND T.PARENT_ITEM_ID IN (
            SELECT I.ITEM_ID FROM ITEM_INFO AS I
                WHERE I.RARITY LIKE 'RARE')
    ORDER BY I.ITEM_ID DESC;